version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/db:/app/db
      - uploads_volume:/app/uploads
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  uploads_volume:
